Added GoRoutines
polisgo2020/Akhmedov_Abdulla pull request #4
Opened 2020-03-29 19:31 UTC by Eretic431

2020-03-31 20:30 UTC, tariel-x commented
Куда делся go.mod?

2020-03-31 20:39 UTC, tariel-x commented
Нужно было параллельно выполнять построение индекса, а не открытие готового индекса.

2020-04-01 15:20 UTC, Eretic431 commented
> Куда делся go.mod?

2020-04-01 15:21 UTC, Eretic431 commented
> Куда делся go.mod?

Да у меня проект в `GOPATH`, случайно видимо удалил

2020-04-01 15:23 UTC, Eretic431 commented
> Нужно было параллельно выполнять построение индекса, а не открытие готового индекса.

блин неправильно понял задание, я исправлю в течении двух дней

2020-04-03 14:12 UTC, Eretic431 commented
@tariel-x исправил

2020-04-04 18:03 UTC, tariel-x requested changes
```
build$ go run main.go 
# github.com/polisgo2020/Akhmedov_Abdulla/invertedIndex
../invertedIndex/invertedIndex.go:62:33: undefined: fie
```

Может, стоит вот [сюда](https://github.com/polisgo2020/Akhmedov_Abdulla/pull/4/files#diff-361cc9049d8dc815e96cc751d25110f3R23) передавать готовый список слов? Это упростит функцию построения индекса.

Там же: файлы желательно читать с диска так же параллельно, это будет даже полезней для быстродействия, чем их параллельная обработка.

Вообще, кажется, что запуск горутины на токен не очень оптимальным решением. Потому что с учётом main, одновременно может обрабатываться не более 7 токенов для 8 ядер. В то же время, запуск и переключение горутины всё же требует очень небольшого, но времени. Скорее всего оптимальней будет, если одна горутина будет писать мапу, а остальные 7 параллельно обрабатывать 7 файлов.

2020-04-04 18:03 UTC, tariel-x commented on invertedIndex/invertedIndex.go
> +				sin.mux.Lock()
Работа уже заблокирована, хотя токен ещё не подготовлен к вставке. Все остальные рутины в этот момент не смогут обработать свои токены, хотя с индексом они ещё не работают.

2020-04-04 18:03 UTC, tariel-x commented on invertedIndex/invertedIndex.go
> +			go func(goToken string, goPosition int) {
Возможно, лучше сделать функцию `func (sin *safeIndex) addToken(token string, position int)`, внутри которой блокировать мьютекс.

2020-04-04 18:04 UTC, tariel-x commented
И всё ещё нет go.mod

2020-04-05 19:15 UTC, Eretic431 commented
Насчет оптимальности обработки каждого токена параллельно, я напишу тесты и почекаю, но что-то мне подсказывает, что вы правы

2020-04-05 19:23 UTC, closed without merging