Dev
polisgo2020/Akhmedov_Abdulla pull request #5
Opened 2020-04-05 19:24 UTC by Eretic431

@tariel-x старая ветка переехала на новую

2020-04-05 21:16 UTC, tariel-x requested changes
```
$ go run -race search.go stop.txt ../build/outputJSON.txt mac sim
==================
WARNING: DATA RACE
Read at 0x00c0008944e0 by goroutine 19:
  github.com/polisgo2020/Akhmedov_Abdulla/invertedIndex.PrintSortedList.func1()
      /home/nikita/go/src/github.com/polisgo2020/Akhmedov_Abdulla/invertedIndex/invertedIndex.go:103 +0x1d9

Previous write at 0x00c0008944e0 by goroutine 18:
  github.com/polisgo2020/Akhmedov_Abdulla/invertedIndex.PrintSortedList.func1()
      /home/nikita/go/src/github.com/polisgo2020/Akhmedov_Abdulla/invertedIndex/invertedIndex.go:103 +0x25d

Goroutine 19 (running) created at:
  github.com/polisgo2020/Akhmedov_Abdulla/invertedIndex.PrintSortedList()
      /home/nikita/go/src/github.com/polisgo2020/Akhmedov_Abdulla/invertedIndex/invertedIndex.go:96 +0x1cf
  main.main()
      /home/nikita/go/src/github.com/polisgo2020/Akhmedov_Abdulla/search/search.go:59 +0x2b4

Goroutine 18 (finished) created at:
  github.com/polisgo2020/Akhmedov_Abdulla/invertedIndex.PrintSortedList()
      /home/nikita/go/src/github.com/polisgo2020/Akhmedov_Abdulla/invertedIndex/invertedIndex.go:96 +0x1cf
  main.main()
      /home/nikita/go/src/github.com/polisgo2020/Akhmedov_Abdulla/search/search.go:59 +0x2b4
==================
==================
WARNING: DATA RACE
Read at 0x00c000542000 by goroutine 19:
  runtime.growslice()
      /usr/local/go/src/runtime/slice.go:76 +0x0
  github.com/polisgo2020/Akhmedov_Abdulla/invertedIndex.PrintSortedList.func1()
      /home/nikita/go/src/github.com/polisgo2020/Akhmedov_Abdulla/invertedIndex/invertedIndex.go:103 +0x2d8

Previous write at 0x00c000542000 by goroutine 18:
  github.com/polisgo2020/Akhmedov_Abdulla/invertedIndex.PrintSortedList.func1()
      /home/nikita/go/src/github.com/polisgo2020/Akhmedov_Abdulla/invertedIndex/invertedIndex.go:103 +0x226

Goroutine 19 (running) created at:
  github.com/polisgo2020/Akhmedov_Abdulla/invertedIndex.PrintSortedList()
      /home/nikita/go/src/github.com/polisgo2020/Akhmedov_Abdulla/invertedIndex/invertedIndex.go:96 +0x1cf
  main.main()
      /home/nikita/go/src/github.com/polisgo2020/Akhmedov_Abdulla/search/search.go:59 +0x2b4

Goroutine 18 (finished) created at:
  github.com/polisgo2020/Akhmedov_Abdulla/invertedIndex.PrintSortedList()
      /home/nikita/go/src/github.com/polisgo2020/Akhmedov_Abdulla/invertedIndex/invertedIndex.go:96 +0x1cf
  main.main()
      /home/nikita/go/src/github.com/polisgo2020/Akhmedov_Abdulla/search/search.go:59 +0x2b4
==================
prisoners - 0.500000
time - 14378.500000
Found 2 data race(s)
exit status 66
```

Попробуйте всё таки сделать отдельную горутину, которая будет читать новые токены из канала писать в индекс. Не факт, что такое решение будет быстрее, чем просто запись, но важно использовать каналы.

2020-04-05 21:16 UTC, tariel-x commented on go.mod
> +module mod
module github.com/polisgo2020/Akhmedov_Abdulla

2020-04-05 21:16 UTC, tariel-x commented on go.mod
> +	github.com/polisgo2020/Akhmedov_Abdulla v0.0.0-20200327132112-01b85dc97dbe // indirect
лишнее

2020-04-05 21:16 UTC, tariel-x commented on invertedIndex/invertedIndex.go
> +		sin.mux.Lock()
Зачем здесь мьютекс и wg, если всё равно всё работает в одной рутине?

2020-04-05 21:16 UTC, tariel-x commented on invertedIndex/invertedIndex.go
>  	for i := 0; i < len(searchPhrase); i++ {
for i := range searchPhrase

2020-04-05 21:16 UTC, tariel-x commented on invertedIndex/invertedIndex.go
> +		filesMap, err = readFiles.ReadFiles(flag, files)
Вопрос: какая из ошибок в итоге окажется в err и не будет ли гонки в случае двух ошибок?

2020-04-05 23:17 UTC, Eretic431 commented on go.mod
> +	github.com/polisgo2020/Akhmedov_Abdulla v0.0.0-20200327132112-01b85dc97dbe // indirect
оно само сгенерилось

2020-04-06 02:39 UTC, Eretic431 commented
не могу понять где у меня гонка
![image](https://user-images.githubusercontent.com/50702744/78518377-ff620580-77c8-11ea-8874-21c7efef992e.png)

2020-04-06 02:40 UTC, Eretic431 commented on go.mod
> +module mod
понял, от имени модуля что-то зависит? А то я не мог понять как его называть

2020-04-06 12:02 UTC, Eretic431 commented on invertedIndex/invertedIndex.go
> +		filesMap, err = readFiles.ReadFiles(flag, files)
последняя, будет, исправил

2020-04-06 12:03 UTC, Eretic431 commented
@tariel-x либо я что-то не так сделал, либо индекс стал строиться медленнее)

2020-04-06 12:03 UTC, Eretic431 commented on invertedIndex/invertedIndex.go
> +		sin.mux.Lock()
и в правду

2020-04-08 23:25 UTC, tariel-x commented on invertedIndex/invertedIndex.go
> +		for {
Если важна только первая ошибка, то for не нужен.

2020-04-08 23:25 UTC, tariel-x commented on invertedIndex/invertedIndex.go
> +	go func() struct{} {
Возвращаемой значение лишнее

2020-04-08 23:25 UTC, tariel-x commented on invertedIndex/invertedIndex.go
> +			select {
select тоже не нужен, здесь нет чтения из нескольких каналов

2020-04-08 23:25 UTC, tariel-x commented on invertedIndex/invertedIndex.go
> +	close(errChannel)
если произошла ошибка, то канал уже закрыт и повторное закрытие вызовет панику: https://play.golang.com/p/cO6572QApAg

2020-04-08 23:25 UTC, tariel-x commented on invertedIndex/invertedIndex.go
> +		return SafeIndex{}, err
Вместо возврата пустой структуры, было бы экономичней возвращать nil в ссылочном возвращаемом параметре.

2020-04-09 17:15 UTC, Eretic431 commented on invertedIndex/invertedIndex.go
> +		return SafeIndex{}, err
> Cannot use 'nil' as type SafeIndex in return argument

2020-04-09 17:30 UTC, Eretic431 reviewed
@tariel-x так мне кажется, или реально медленнее стало работать

2020-04-09 17:30 UTC, Eretic431 commented on invertedIndex/invertedIndex.go
> +		return SafeIndex{}, err
а, вы хотите чтоб я по ссылке структуру возвращал

2020-04-09 17:31 UTC, Eretic431 reviewed
готово

2020-04-09 21:19 UTC, tariel-x reviewed
Надо исправить ещё 2 пункта и можно мержить.

2020-04-09 21:19 UTC, tariel-x commented on invertedIndex/invertedIndex.go
> +	// я не понимаю почему, но если я пишу тут этот if у меня не заканчивается работа программы
Потому что канал не закрыт, но в него никто не пишет Поэтому deadlock. Можно сделать так:
Сделать буферизированный канал с буфером по количеству горутин, чтоб каждая могла записать ошибку и сделать wg.Done
Сразу после wg.Done закрыть канал. Уже записанные данные в нём останутся.
После закрытия канала с ошибками можно один раз прочитать из него err или получить ok == false. Второе будет означать, что канал закрылся пустым.

Сейчас, кстати, сложно предсказать, может ли произойти ситуация, когда какая-то горутина записала ошибку, wg.Done произошло, проверка на nil произошла а горутина для ловли ещё не успела отработать.

2020-04-09 21:19 UTC, tariel-x commented on invertedIndex/invertedIndex.go
> +	for {
Внизу лишнюю конструкцию убрали, а здесь что.

2020-04-10 17:29 UTC, Eretic431 commented
Вроде все

2020-04-10 17:32 UTC, Eretic431 commented on invertedIndex/invertedIndex.go
> +	// я не понимаю почему, но если я пишу тут этот if у меня не заканчивается работа программы
после `wg.Wait()` вы имели в виду?

2020-04-10 17:32 UTC, Eretic431 commented on invertedIndex/invertedIndex.go
> +	for {
упс

2020-04-10 17:57 UTC, Eretic431 commented on invertedIndex/invertedIndex.go
> +	for {
так здесь нужен `for`, мне же надо постоянно токены принимать

2020-04-10 17:58 UTC, Eretic431 commented on invertedIndex/invertedIndex.go
> +	for {
`select` убрал

2020-04-10 19:20 UTC, tariel-x commented on invertedIndex/invertedIndex.go
> +	for {
Для этого ведь есть range, который сам выходит из цикла, когда канал закрывается. https://github.com/polisgo2020/main/blob/master/src/lec3/chan/2/chan_2.go#L20

2020-04-10 19:20 UTC, tariel-x commented on invertedIndex/invertedIndex.go
> +	// я не понимаю почему, но если я пишу тут этот if у меня не заканчивается работа программы
Да, закрыть канал после wg.Wait

2020-04-10 19:21 UTC, tariel-x commented on invertedIndex/invertedIndex.go
> +	for {
Для этого ведь есть range, который сам выходит из цикла, когда канал закрывается. https://github.com/polisgo2020/main/blob/master/src/lec3/chan/2/chan_2.go#L20

2020-04-10 21:26 UTC, tariel-x approved these changes

2020-04-11 07:32 UTC, merged